### Welcome message to check the database is set up
GET http://localhost:8080/api/info

#### USER ENDPOINTS #####

### Updates an existing person
PUT http://localhost:8080/api/users/ole123
Content-Type: application/json

{
  "userPass": "test",
  "userEmail": "test@test.com"
}

### List of all users
GET http://localhost:8080/api/users/all
Content-Type: application/json

### System greets the admin in this case, if he's logged in
GET http://localhost:8080/api/info/admin
x-access-token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2NjcyOTYyMTAsImlhdCI6MTY2NzI5NDQxMCwiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.dlsMNiQc_OYU2HCa-WMzNImQ3qoNy2CGXEWAbXBQM3g"

### Creates a new person
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "userName": "ole123",
  "userEmail": "chris@gmail.com",
  "userPass": "test123"
}

###
POST http://localhost:8080/api/users/add/userfar/1
Content-Type: application/json

### Deletes an existing person
DELETE http://localhost:8080/api/users/user
Content-Type: application/json





##### TRAINING SESSION ENDPOINT: #######

### Delete Training session
DELETE http://localhost:8080/api/training/3
Content-Type: application/json

### Create trainingsession
POST http://localhost:8080/api/training
Content-Type: application/json

{
  "title": "I created this through demo.http",
  "time": "08:10",
  "date": "2022-10-21",
  "fullAddress": "Stabilvej 2",
  "category": {
    "id": 1
  },
  "maxParticipants": 15
}

### Update trainingsesssion
PUT http://localhost:8080/api/training/update
Content-Type: application/json

{
  "id": 1,
  "title": "I updated this through demo.http",
  "time": "08:10",
  "date": "2022-10-21",
  "fullAddress": "Stabilvej 2",
  "category": {
    "id": 2
  },
  "maxParticipants": 15
}

### Get by id
GET http://localhost:8080/api/training/get/1
Content-Type: application/json

### Get all
GET http://localhost:8080/api/training/all
Content-Type: application/json

###