### Welcome message to check the database is set up
GET http://localhost:8080/api/info

### Updates an existing person
PUT http://localhost:8080/api/users/chris
Content-Type: application/json

{
  "userPass": "test"
}

### List of all users
GET http://localhost:8080/api/users/all
Content-Type: application/json

### System greets the admin in this case, if he's logged in
GET http://localhost:8080/api/info/admin
x-access-token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2NjcyOTYyMTAsImlhdCI6MTY2NzI5NDQxMCwiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.dlsMNiQc_OYU2HCa-WMzNImQ3qoNy2CGXEWAbXBQM3g"

### Creates a new person
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "userName": "chris",
  "userPass": "test123"
}

### Deletes an existing person
DELETE http://localhost:8080/api/users/chris
Content-Type: application/json

